version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y unzip curl
  build:
    commands:
      - echo Pulling appspec.yml from GitHub...
      - curl -L https://raw.githubusercontent.com/campusx-official/mlops-mini-project/main/appspec.yml -o appspec.yml

      - echo Pulling install_dependencies.sh from GitHub...
      - curl -L https://raw.githubusercontent.com/campusx-official/mlops-mini-project/main/deploy/scripts/install_dependencies.sh -o install_dependencies.sh

      - echo Pulling start_docker.sh from GitHub...
      - curl -L https://raw.githubusercontent.com/campusx-official/mlops-mini-project/main/deploy/scripts/start_docker.sh -o start_docker.sh

      - echo Uploading appspec.yml to S3...
      - aws s3 cp appspec.yml s3://campusxcodebuildbucket/appspec.yml

      - echo Uploading install_dependencies.sh to S3...
      - aws s3 cp install_dependencies.sh s3://campusxcodebuildbucket/deploy/scripts/install_dependencies.sh

      - echo Uploading start_docker.sh to S3...
      - aws s3 cp start_docker.sh s3://campusxcodebuildbucket/deploy/scripts/start_docker.sh